language: cpp
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get install -y cmake
    - sudo apt-get install -y unzip
    - sudo apt-get install -y glfw glfw-dev
script: ./pake.py gravity
