language: cpp
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get install -y cmake
    - sudo apt-get install -y unzip
    - curl -o ../gmock-1.7.0.zip -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
    - unzip ../gmock-1.7.0.zip -d ..
    - cd ../gmock-1.7.0
    - cmake .
    - make
    - sudo make install
    - cd -
before_script: cmake .
script: make all
after_script: ctest -V
