language: cpp

compiler:
    - clang
    - gcc

before_install:
    # g++4.9
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # clang 3.5
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

    # set PAKE config
    - if [ "$CXX" == "clang++" ]; then  PAKE_CONFIG="clang" ; fi
    - if [ "$CXX" == "g++" ]; then export PAKE_CONFIG="gcc" ; fi
    - sudo apt-get install -y libglfw2 libglfw-dev
    - sudo apt-get update -qq

install:
    # g++4.9
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

    # clang 3.5
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.5; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

before_script:
    - echo $PAKE_CONFIG
    - echo $CXX

script:
    - python pake.py gravity -c $PAKE_CONFIG
